debug: true

logging:
  level:
    org:
      hibernate: trace

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/.h2/shiro-oauth2-db
    driver-class-name: org.h2.Driver
    username: oauth2
    password: oauth2
    type: org.apache.commons.dbcp2.BasicDataSource
    data: classpath:/persistent/h2/dml-insert-20190313.sql

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console/oauth2-db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    prefix: classpath:/frontend/
    suffix: .html
    cache: false
